apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/naima90/eks-deployment.git
    targetRevision: main
    path: infra/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: eks-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      # syncOptions:
      # - CreateNamespace=true


