apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: naimaosman203@gmail.com
    privateKeySecretRef:
      name: issuer
    solvers:
      - dns01:
          route53:
            hostedZoneID: Z0315154WU3KKSUXF4G5
            region: eu-west-2
        selector:
          dnsZones:
          - lab.naimaosmann.com
      - http01:
          ingress:
            class: nginx
